### ISSUE TITLE
dynamic-plot-0.1.2.0 cannot be installed due to unsatisfied dependencies

### ISSUE THREAD

**Issue by redneb** [leftaroundabout/dynamic-plot#1]
`dynamic-plot-0.1.2.0` depends on `diagrams-cairo (>1.3.0.5 && <1.4)`, but there is no such version of `diagrams-cairo` available on hackage (`1.3.0.5` is the latest available).

**Comment by leftaroundabout** [comment]
That's right. The latest version on Hackage ([diagrams-cairo-1.3.0.5](http://hackage.haskell.org/package/diagrams-cairo-1.3.0.4)) had removed text support, which dynamic-plot needs. [I have pushed this back in](https://github.com/diagrams/diagrams-cairo/commit/8c7c3acf5ea57db92de8eff92fde882e57020b1c), but the diagrams guys haven't made a new release since. Pull [the `HEAD` version off their Github repo](https://github.com/diagrams/diagrams-cairo), that should work.

(Unless you're stuck on [this issue with `manifolds`](https://github.com/leftaroundabout/manifolds/issues/2) you pointed out; I'll have to look into this.)
