### ISSUE TITLE
Panning via dragging

### ISSUE THREAD

**Issue by redneb** [leftaroundabout/dynamic-plot#2]
It would be nice to allow panning via dragging the view with the mouse, similar to how google maps works.

**Comment by leftaroundabout** [comment]
I actually designed the zoom/scroll behaviour deliberately so this wouldn't be necessary. Scrolling out does not zoom around the mouse but around the _opposite_ focal point, so you can quite easily &ldquo;crawl along&rdquo; by zooming out an in again near a screen edge. Especially for larger distances, this is more effecient than click-and-move, because the zooming gives you exponential step size. After some experience with this, I regularly wish Google Maps had this behaviour too!

![crawl-scrolling](https://cloud.githubusercontent.com/assets/1528675/14791103/9c71a20c-0b14-11e6-98da-ea86ec059eef.gif)

That said... I'm not altogether happy with the navigation features yet, either. In particular, the zooming messes up the aspect ratio, which is certainly a problem in many applications.

'll consider some changes. But I don't think I'd like grab&drag panning, also because it fix-assigns mouse clicks to a built-in feature. I'd like to keep clicks completely free so one can use them to e.g. drag around objects dynamically, at some point.

**Comment by redneb** [comment]
> Scrolling out does not zoom around the mouse but around the opposite focal point, so you can quite easily “crawl along” by zooming out an in again near a screen edge.

I did notice that and it's useful sometimes, but I would still prefer the google maps behavior for some situations.

> But I don't think I'd like grab&drag panning, also because it fix-assigns mouse clicks to a built-in feature. I'd like to keep clicks completely free so one can use them to e.g. drag around objects dynamically, at some point.

That can be addressed by introducing different modes for mouse clicks. Or better yet, you could use middle click dragging for panning. This is what GIMP and inkscape do.

**Comment by leftaroundabout** [comment]
Fine, [here you go then](https://github.com/leftaroundabout/dynamic-plot/commit/3b307c5bba2e053e57e18fb96aca093f0e4ee4d4). (Please test it, I don't have a mouse with middle button to do so...)

**Comment by redneb** [comment]
Thanks, it works fine.
